apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-issuer
  namespace: cert-manager
spec:
  project: default
  source:
    repoURL: 'https://github.com/Merliteam-ok/Mindlab-deploy.git'
    targetRevision: HEAD
    path: certificate
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true