apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-fe
  namespace: dev
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-fe
  template:
    metadata:
      labels:
        app: chatbot-fe
        vers: "92"
    spec:
      containers:
        - name: frontend
          image: 026090511617.dkr.ecr.us-east-2.amazonaws.com/mindlab-dev:chatbot-fe-latest
          imagePullPolicy: Always
          env:
          - name: VITE_API_URL
            value: "https://api.dev.app.mind-lab.ai"
          ports:
            - containerPort: 3005
      imagePullSecrets:
        - name: ecr-secret
