apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mi-react-app
  template:
    metadata:
      labels:
        app: mi-react-app
    spec:
      containers:
        - name: mi-react-app
          image: 123456789012.dkr.ecr.us-east-2.amazonaws.com/mi-react-app:latest
          ports:
            - containerPort: 80
