apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-api
  namespace: prod
spec:
  revisionHistoryLimit: 0
  replicas: 1
  selector:
    matchLabels:
      app: chatbot-api
  template:
    metadata:
      labels:
        app: chatbot-api
        vers: "44"
    spec:
      containers:
      - name: chatbot-api
        # image: 026090511617.dkr.ecr.us-east-2.amazonaws.com/mindlab-main:chatbot-api-latest
        image: 026090511617.dkr.ecr.us-east-2.amazonaws.com/mindlab-prod:chatbot-api-latest
        # image: 026090511617.dkr.ecr.us-east-2.amazonaws.com/mindlab/ai-agents-manager/admin-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3001
        env:
        - name: REDIS_HOST
          value: "redis.prod.svc.cluster.local"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_USER
          value: "default"
        - name: REDIS_PASSWORD
          value: "merliteam2024"
        - name: REDIS_TLS
          value: "false"
        - name: FRONT_DASHBOARD_URL
          value: "https://app.mind-lab.ai"

      imagePullSecrets:
      - name: ecr-secret
