apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot-api
  namespace: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatbot-api
  template:
    metadata:
      labels:
        app: chatbot-api
    spec:
      containers:
      - name: chatbot-api
        image: 026090511617.dkr.ecr.us-east-2.amazonaws.com/my-k8s-cluster:chatbot-api-prod
        ports:
        - containerPort: 3001
        env:
        - name: REDIS_HOST
          value: "redis.dev.mind-lab.ai"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: "merliteam2024"
      imagePullSecrets:
      - name: ecr-secret
