apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: prod
spec:
  selector:
    app: chatbot-api
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3001
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: landing-fe-svc
  namespace: prod
spec:
  selector:
    app: landing-fe
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 3000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: landing-be-svc
  namespace: prod
spec:
  selector:
    app: landing-be
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 1337
  type: ClusterIP