apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: prod
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80           # El puerto en el que se expone el servicio
      targetPort: 8080   # El puerto donde tu aplicación escucha dentro del pod
  type: LoadBalancer     # Para exponer el servicio externamente (AWS crea un ELB automáticamente)
